Repository ShettyGaneshprasad/SDLC_27_PatientVaccineManagement, pull requests merged in 2021-08, with the labels that each got.

#2 SWOT Analysis
  README.md
Labels: documentation

#5 Added folder structure
  .gitignore
  1_Requirements/README.md
  2_Architecture/README.md
  3_Implementation/README.md
  4_TestPlanAndOutput/README.md
  5_Report/README.md
  6_ImagesandVideos/README.md
  7_Data/README.md
Labels: documentation

#18 Added low level & high level requirement
  1_Requirements/README.md
Labels: documentation

#28 added new banner and created testplan
  1_Requirements/pvmsbanner.jpg
  4_TestPlanAndOutput/README.md
Labels: documentation

#30 Adding architecture diagram readme
  2_Architecture/README.md
  README.md
Labels: documentation

#72 Adding Feature of deleting patient
  3_Implementation/src/delete_all.c
  3_Implementation/src/indexFile.c
Labels: enhancement

#74 Feature deleting patient
  3_Implementation/src/delete_all.c
  3_Implementation/src/indexFile.c
Labels: enhancement

#98 name refrence error resolved
  .gitignore
  3_Implementation/inc/vaccination.h
  3_Implementation/main.c
  3_Implementation/src/create_patientid.c
  3_Implementation/src/patient_loadData.c
  3_Implementation/test/test.c
Labels: bug

#101 Adding workflow
  .github/ISSUE_TEMPLATE/GIT_Inspector.yml
  .github/ISSUE_TEMPLATE/TEST-Unity.yml
  .github/ISSUE_TEMPLATE/c-Build-Linux.yml
  .github/ISSUE_TEMPLATE/c-Build-Windows.yml
  .github/ISSUE_TEMPLATE/codeCoverage.yml
  .github/ISSUE_TEMPLATE/codeQualityDynamic.yml
  .github/ISSUE_TEMPLATE/codeQualityStatic.yml
Labels: enhancement

#134 added Doxygen comments in missing place
  3_Implementation/main.c
  3_Implementation/src/delete_patientrecords_file.c
  3_Implementation/src/display_patientid.c
  3_Implementation/src/find_by_patientid.c
  3_Implementation/src/insert_patientrecords.c
  3_Implementation/src/patient_loadData.c
  3_Implementation/src/patient_saveFile.c
  3_Implementation/src/update_patient_data_file.c
  3_Implementation/src/update_patientrecord.c
  3_Implementation/src/validate_patientid.c
  3_Implementation/test/test.c
Labels: fix
